version: '3.6'
services:
  # MongoDB
  studentdb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db/student
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'

  # API
  student:
    build:
      context: ./student
      target: dev
    restart: always
    volumes:
      - ./student:/student
    ports:
      - '3000:3000'
    links:
      - studentdb
    depends_on:
      - studentdb
    env_file:
      - ./student/.env

volumes:
  mongodb-data:
